CREATE TABLE Empleados (
	ID INT PRIMARY KEY IDENTITY(1,1),
	NOMBRES VARCHAR(50) NOT NULL,
	DPI BIGINT NOT NULL,
	NACIMIENTO DATE NOT NULL,
	GENERO VARCHAR(50) NOT NULL,
	INGRESO_EMPRESA DATE NOT NULL,
	EDAD INT NOT NULL,
	DIRECCION VARCHAR(50),
	NIT INT,
	DEPARTAMENTO VARCHAR(50) NOT NULL
)