USE dbPERFILES;
/*
SELECT * FROM Empleados;
*/
/*
SELECT * FROM Empleados
WHERE ID = 2;
*/
SELECT * FROM Empleados
WHERE NOMBRES LIKE '%JON%';
/*
SELECT * FROM Empleados
WHERE DEPARTAMENTO = 'RECURSOS HUMANOS';
*/